version: 0.0
os: linux

files:
– source: build/
destination: /var/www/html

permissions:
  - object: /var/www/html
    owner: root
    group: root
    mode: 755
    type:
      - directory
  - object: /var/www/html
    owner: root
    group: root
    mode: 644
    type:
      - file