version: 0.2

phases:
  install:
    commands:
      - node -v
      - npm -v
      - yarn -v
  pre_build:
    commands:
      - echo Entring app directory
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
#      - aws s3 sync build/ s3://my-bucket-xiaomo --exclude '*.DS_Store' --acl public-read --cache-control public,max-age=604800
artifacts:
  files:
    - 'build/*'
    - 'appspec.yml'
  base-directory: my-app/build
